### ISSUE TITLE
成就及其它服务以后会支持吗

### ISSUE THREAD

**Issue by HaiboLee** [xiSage/Godot4-TapTap-SDK-v4#1]
成就及其它服务以后会支持吗

**Comment by xiSage** [comment]
这个项目是在原来的v3插件基础上编写的，目标是与之前的插件接口兼容。过几天我会另开一个项目，按TapSDK的模块分成多个插件，实现更贴合TapSDK接口的封装，并且尽可能提供TapSDK的全部功能。
